name: build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v6
      - run: pacman -Syu --needed --noconfirm base-devel git

      - run: echo WORKDIR=$(pwd) | tee -a $GITHUB_ENV

      - run: useradd -m builder
      - run: "echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
      - run: chown builder -R $WORKDIR

      - name: libjwt
        run: |
          su -s/bin/bash - builder << EOF
          set -e
          git clone https://aur.archlinux.org/libjwt.git /tmp/libjwt
          cd /tmp/libjwt
          makepkg -si --noconfirm
          ls ./libjwt-*.pkg.tar.zst
          EOF

      - name: sso-mib
        run: |
          su -s/bin/bash - builder << EOF
          set -e
          cd $WORKDIR/sso-mib
          makepkg -si --noconfirm
          ls ./sso-mib-*.pkg.tar.zst
          EOF

      - name: freerdp-sso-mib
        run: |
          su -s/bin/bash - builder << EOF
          set -e
          cd $WORKDIR/freerdp-sso-mib
          makepkg -si --noconfirm
          ls ./freerdp-sso-mib-*.pkg.tar.zst
          EOF

      - name: rdpmib
        run: |
          su -s/bin/bash - builder << EOF
          set -e
          cd $WORKDIR/rdpmib
          makepkg -si --noconfirm
          ls ./rdpmib-*.pkg.tar.zst
          EOF

      - name: prepare
        run: |
          echo FILES=$(find /tmp/libjwt $WORKDIR -name '*.pkg.tar.zst' | xargs) | tee -a $GITHUB_ENV
          echo RELEASE_NAME=$(date -Iminutes) | tee -a $GITHUB_ENV

      - run: echo $RELEASE_NAME $FILES

      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}
          files: ${{ env.FILES }}
