name: build

on:
  push: # TODO for test

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v6
      - run: pacman -Syu --needed --noconfirm base-devel
      - run: useradd -m builder
      - run: "echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
      - run: |
          cd $(mktemp -d)
          git clone https://aur.archlinux.org/libjwt.git
          makepkg -si
          ls ./libjwt-*.pkg.tar.zst
